name: SpeedReader
options:
  bundleIdPrefix: com.quickspec
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  SpeedReader:
    type: application
    platform: macOS
    sources:
      - path: SpeedReader
        excludes:
          - "*.h"
      - path: ../generated/SwiftBridgeCore.swift
      - path: ../generated/speed-reader-core/speed-reader-core.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.quickspec.speedreader
        PRODUCT_NAME: Speed Reader
        INFOPLIST_FILE: SpeedReader/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: SpeedReader/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - $(PROJECT_DIR)/../generated
          - $(PROJECT_DIR)/../generated/speed-reader-core
        LIBRARY_SEARCH_PATHS:
          - $(PROJECT_DIR)/../target/release
        OTHER_LDFLAGS:
          - -lspeed_reader_core
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
