name: Skim
options:
  bundleIdPrefix: com.quickspec
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  Skim:
    type: application
    platform: macOS
    sources:
      - path: Skim
        excludes:
          - "*.h"
      - path: ../generated/SwiftBridgeCore.swift
      - path: ../generated/skim-core/skim-core.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.quickspec.skim
        PRODUCT_NAME: Skim
        INFOPLIST_FILE: Skim/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Skim/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - $(PROJECT_DIR)/../generated
          - $(PROJECT_DIR)/../generated/skim-core
        OTHER_LDFLAGS:
          - -lskim_core
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          LIBRARY_SEARCH_PATHS:
            - $(PROJECT_DIR)/../target/debug
        Release:
          LIBRARY_SEARCH_PATHS:
            - $(PROJECT_DIR)/../target/release
